# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temptingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templog',
            name='total_cook_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
