# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temptingApp', '0002_auto_20160913_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templog',
            name='total_cook_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
