# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temptingApp', '0005_auto_20160919_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templog',
            name='total_cook_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
