# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temptingApp', '0006_auto_20160920_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templog',
            old_name='total_cook_time',
            new_name='end_date',
        ),
    ]
